-- PERSONNEL DATA
INSERT INTO PERSONNEL(PERSON_ID, FIRST_NAME, LAST_NAME, EMAIL, P_RANK, SALARY, TAXCODE, PERSONNEL_STAFF_FLAG, PROJECT_STAFF_FLAG, PROJECT_MANAGER_FLAG, PERSONNEL_MANAGER_FLAG, DIRECTOR_FLAG) 
    VALUES('00001', 'Hoàng An', 'Phạm', '', 'MANAGER', 500000000, '10001', 0, 0, 0, 0, 1);
    
INSERT INTO PERSONNEL(PERSON_ID, FIRST_NAME, LAST_NAME, EMAIL, P_RANK, SALARY, TAXCODE, PERSONNEL_STAFF_FLAG, PROJECT_STAFF_FLAG, PROJECT_MANAGER_FLAG, PERSONNEL_MANAGER_FLAG, DIRECTOR_FLAG) 
    VALUES('00002', 'Nhân', 'Nguyễn Văn', '', 'MANAGER', 50000000, '10002', 0, 0, 0, 1, 0);
    
INSERT INTO PERSONNEL(PERSON_ID, FIRST_NAME, LAST_NAME, EMAIL, P_RANK, SALARY, TAXCODE, PERSONNEL_STAFF_FLAG, PROJECT_STAFF_FLAG, PROJECT_MANAGER_FLAG, PERSONNEL_MANAGER_FLAG, DIRECTOR_FLAG) 
    VALUES('00003', 'Minh Nhân', 'Huỳnh', '', 'STAFF', 15000000, '10003', 1, 0, 0, 0, 0);
    
INSERT INTO PERSONNEL(PERSON_ID, FIRST_NAME, LAST_NAME, EMAIL, P_RANK, SALARY, TAXCODE, PERSONNEL_STAFF_FLAG, PROJECT_STAFF_FLAG, PROJECT_MANAGER_FLAG, PERSONNEL_MANAGER_FLAG, DIRECTOR_FLAG) 
    VALUES('00004', 'Trọng Nhân', 'Phạm', '', 'STAFF', 15000000, '10004', 1, 0, 0, 0, 0);
    
INSERT INTO PERSONNEL(PERSON_ID, FIRST_NAME, LAST_NAME, EMAIL, P_RANK, SALARY, TAXCODE, PERSONNEL_STAFF_FLAG, PROJECT_STAFF_FLAG, PROJECT_MANAGER_FLAG, PERSONNEL_MANAGER_FLAG, DIRECTOR_FLAG) 
    VALUES('00005', 'Tài', 'Phan', '', 'MANAGER', 50000000, '10005', 0, 0, 1, 0, 0);
    
INSERT INTO PERSONNEL(PERSON_ID, FIRST_NAME, LAST_NAME, EMAIL, P_RANK, SALARY, TAXCODE, PERSONNEL_STAFF_FLAG, PROJECT_STAFF_FLAG, PROJECT_MANAGER_FLAG, PERSONNEL_MANAGER_FLAG, DIRECTOR_FLAG) 
    VALUES('00006', 'Tài An', 'Huỳnh', '', 'Manager', 50000000, '10006', 0, 0, 1, 0, 0);
