-- PERSONNEL DATA
INSERT INTO PERSONNEL(PERSON_ID, FIRST_NAME, LAST_NAME, EMAIL, P_RANK, SALARY, TAXCODE, DIRECTOR_FLAG, PERSONNEL_MANAGER_FLAG, NORMAL_MANAGER_FLAG, PERSONNEL_STAFF_FLAG, NORMAL_STAFF_FLAG) 
    VALUES('00001', 'Hoàng An', 'Phạm', '', 'MANAGER', 500000000, '10001', 1, 0, 0, 0, 0);
    
INSERT INTO PERSONNEL(PERSON_ID, FIRST_NAME, LAST_NAME, EMAIL, P_RANK, SALARY, TAXCODE, DIRECTOR_FLAG, PERSONNEL_MANAGER_FLAG, NORMAL_MANAGER_FLAG, PERSONNEL_STAFF_FLAG, NORMAL_STAFF_FLAG) 
    VALUES('00002', 'Nhân', 'Nguyễn Văn', '', 'MANAGER', 50000000, '10002', 0, 1, 0, 0, 0);
    
INSERT INTO PERSONNEL(PERSON_ID, FIRST_NAME, LAST_NAME, EMAIL, P_RANK, SALARY, TAXCODE, DIRECTOR_FLAG, PERSONNEL_MANAGER_FLAG, NORMAL_MANAGER_FLAG, PERSONNEL_STAFF_FLAG, NORMAL_STAFF_FLAG) 
    VALUES('00003', 'Minh Nhân', 'Huỳnh', '', 'STAFF', 15000000, '10003', 0, 0, 0, 1, 0);
    
INSERT INTO PERSONNEL(PERSON_ID, FIRST_NAME, LAST_NAME, EMAIL, P_RANK, SALARY, TAXCODE, DIRECTOR_FLAG, PERSONNEL_MANAGER_FLAG, NORMAL_MANAGER_FLAG, PERSONNEL_STAFF_FLAG, NORMAL_STAFF_FLAG) 
    VALUES('00004', 'Trọng Nhân', 'Phạm', '', 'STAFF', 15000000, '10004', 0, 0, 0, 1, 0);
    
INSERT INTO PERSONNEL(PERSON_ID, FIRST_NAME, LAST_NAME, EMAIL, P_RANK, SALARY, TAXCODE, DIRECTOR_FLAG, PERSONNEL_MANAGER_FLAG, NORMAL_MANAGER_FLAG, PERSONNEL_STAFF_FLAG, NORMAL_STAFF_FLAG) 
    VALUES('00005', 'Tài', 'Phan', '', 'MANAGER', 50000000, '10005', 0, 0, 1, 0, 0);
    
INSERT INTO PERSONNEL(PERSON_ID, FIRST_NAME, LAST_NAME, EMAIL, P_RANK, SALARY, TAXCODE, DIRECTOR_FLAG, PERSONNEL_MANAGER_FLAG, NORMAL_MANAGER_FLAG, PERSONNEL_STAFF_FLAG, NORMAL_STAFF_FLAG) 
    VALUES('00006', 'Tài An', 'Huỳnh', '', 'MANAGER', 50000000, '10006', 0, 0, 1, 0, 0);
